git clone https://github.com/the-cult-of-integral/discord-raidkit
git clone https://github.com/AsjadOooO/Zero-attacker
git clone https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot
git clone https://github.com/17teen/Discord-Presser-Server-Nuker
git clone https://github.com/Walkoud/raidbotdiscord
git clone https://github.com/nukebot/discord-nuke-bot
git clone https://github.com/CapingTeam/All-Ban-Tool
git clone https://github.com/ICEGXG/UntitledNuker
git clone https://github.com/9P9/Discord-Nuker
git clone https://github.com/CorruptedBytes/DiscordGriefBot
git clone https://github.com/Jansy-cc/Discord-Nuke-Bot
git clone https://github.com/KMKINGMAN/Raid-Bot-TS
git clone https://github.com/TheAxes/Discord-Nuke-Bot
git clone https://github.com/KaTuKas1/DiscordNukeBot
git clone https://github.com/TheAxes/Discord-Nuke-Bot-V2
git clone https://github.com/TheAxes/Discord-Nuke-Bot-V3
git clone https://github.com/priyanshu9588/Seesh-Nuker
git clone https://github.com/miltinhoc/Discord-Nuker
git clone https://github.com/ItzmeKen/Xmas-Attacker
git clone https://github.com/AsjadOooO/Discord-Nuker
git clone https://github.com/albertopoljak/Genetic-Lifeform-and-Disk-Operating-System
git clone https://github.com/bastianleicht/GriefBotDiscord
git clone https://github.com/team-v0rtex/ax0n2nuker
git clone https://github.com/Noface404/Oxyg3n-Nuker
git clone https://github.com/Pol528/gbot
git clone https://github.com/N0t-Ex1st/Discrash
git clone https://github.com/Giulio105/NUKER-13-DISCORD-NUKER-BETA
git clone https://github.com/Giulio105/demonnuker
git clone https://github.com/Tira-tw/Best-Nuke-Bot
git clone https://github.com/miltinhoc/Discord-Nuker
git clone https://github.com/ItzmeKen/Xmas-Attacker
git clone https://github.com/natrixdev/Discord-Nuke-Bot
git clone https://github.com/ultimus2935/Exinor
git clone https://github.com/CalderJohnson/discord-nuke-bot-v2
git clone https://github.com/Z4nzu/hackingtool
git clone https://github.com/nullsecuritynet/tools
git clone https://github.com/LasCC/Hack-Tools
git clone https://github.com/carpedm20/awesome-hacking
git clone https://github.com/hacktoolspack/hack-tools
git clone https://github.com/sundowndev/hacker-roadmap
git clone https://github.com/dreddsa5dies/goHackTools
git clone https://github.com/mishakorzik/AllHackingTools
git clone https://github.com/thehackingsage/hacktronian
git clone https://github.com/cr0hn/dockerscan
git clone https://github.com/chinoogawa/fbht
git clone https://github.com/AnonHackerr/toolss
git clone https://github.com/AdrMXR/KitHack
git clone https://github.com/xiaoyanguoke/CIAHackingTools
git clone https://github.com/dsasmblr/game-hacking
git clone https://github.com/ckjbug/Hacking
git clone https://github.com/Gexos/Hacking-Tools-Repository
git clone https://github.com/hhhrrrttt222111/Ethical-Hacking-Tools
git clone https://github.com/esc0rtd3w/wifi-hacker
git clone https://github.com/jgamblin/CarHackingTools
git clone https://github.com/entropy1337/infernal-twin
git clone https://github.com/Harveysn0w/CTF_Hacker-Tools
git clone https://github.com/s7ckTeam/HackTools
git clone https://github.com/hahwul/WebHackersWeapons
git clone https://github.com/laxa/HackingTools
git clone https://github.com/0x90/bluetooth-arsenal
git clone https://github.com/Edu4rdSHL/findomain
git clone https://github.com/Edu4rdSHL/findomain
git clone https://github.com/g0tmi1k/msfpc
git clone https://github.com/g0tmi1k/msfpc 
git clone https://github.com/galauerscrew/hasherdotid
git clone https://github.com/galauerscrew/hasherdotid 
git clone https://github.com/galkan/crowbar
git clone https://github.com/galkan/crowbar 
git clone https://github.com/Gameye98/AstraNmap
git clone https://github.com/Gameye98/AstraNmap 
git clone https://github.com/Gameye98/Auxscan
git clone https://github.com/Gameye98/Auxscan 
git clone https://github.com/Gameye98/Black-Hydra
git clone https://github.com/Gameye98/Black-Hydra 
git clone https://github.com/Gameye98/FaDe
git clone https://github.com/Gameye98/FaDe 
git clone https://github.com/Gameye98/GINF
git clone https://github.com/Gameye98/GINF 
git clone https://github.com/Gameye98/inther
git clone https://github.com/Gameye98/inther 
git clone https://github.com/Gameye98/Lazymux
git clone https://github.com/Gameye98/Lazymux 
git clone https://github.com/Gameye98/OWScan
git clone https://github.com/Gameye98/OWScan 
git clone https://github.com/Gameye98/santet-online
git clone https://github.com/Gameye98/santet-online 

git clone https://github.com/gdabah/distorm
git clone https://github.com/gdabah/distorm 
git clone https://github.com/GDSSecurity/wifitap
git clone https://github.com/GDSSecurity/wifitap 

git clone https://github.com/gitdurandal/dbd
git clone https://github.com/gitdurandal/dbd 

git clone https://github.com/gkbrk/slowloris
git clone https://github.com/gkbrk/slowloris 
git clone https://github.com/golismero/golismero
git clone https://github.com/golismero/golismero 
git clone https://github.com/googleinurl/SCANNER-INURLBR
git clone https://github.com/googleinurl/SCANNER-INURLBR 
git clone https://github.com/GoogleX133/GoogleSearch-CLI
git clone https://github.com/GoogleX133/GoogleSearch-CLI 
git clone https://github.com/govolution/avet
git clone https://github.com/govolution/avet 
git clone https://github.com/grafov/hulk
git clone https://github.com/grafov/hulk 
git clone https://github.com/greenbone/openvas
git clone https://github.com/greenbone/openvas 
git clone https://github.com/Ha3MrX/Gemail-Hack
git clone https://github.com/Ha3MrX/Gemail-Hack 
git clone https://github.com/HA71/Namechk
git clone https://github.com/HA71/Namechk 
git clone https://github.com/hacdias/webdav
git clone https://github.com/hacdias/webdav 
git clone https://github.com/Hackplayers/4nonimizer
git clone https://github.com/Hackplayers/4nonimizer 
git clone https://github.com/the-robot/sqliv
git clone https://github.com/the-robot/sqliv 
git clone https://github.com/hashcat/hashcat
git clone https://github.com/hashcat/hashcat 
git clone https://github.com/hashcat/maskprocessor
git clone https://github.com/hashcat/maskprocessor 
git clone https://github.com/hatRiot/zarp
git clone https://github.com/hatRiot/zarp 
git clone https://github.com/Hax4us/Metasploit_termux
git clone https://github.com/Hax4us/Metasploit_termux 
git clone https://github.com/Hax4us/Nethunter-In-Termux
git clone https://github.com/Hax4us/Nethunter-In-Termux 
git clone https://github.com/Hax4us/TermuxAlpine
git clone https://github.com/Hax4us/TermuxAlpine 

git clone https://github.com/Hood3dRob1n/BinGoo
git clone https://github.com/Hood3dRob1n/BinGoo 

git clone https://github.com/i3visio/osrframework
git clone https://github.com/i3visio/osrframework 
git clone https://github.com/ihebski/angryFuzzer
git clone https://github.com/ihebski/angryFuzzer 
git clone https://github.com/ikkebr/PyBozoCrack
git clone https://github.com/ikkebr/PyBozoCrack 
git clone https://github.com/infobyte/faraday
git clone https://github.com/infobyte/faraday 
git clone https://github.com/iniqua/plecost
git clone https://github.com/iniqua/plecost 
git clone https://github.com/nccgroup/keimpx
git clone https://github.com/nccgroup/keimpx 
git clone https://github.com/iSECPartners/sslyze
git clone https://github.com/iSECPartners/sslyze 
git clone https://github.com/JamesJGoodwin/wreckuests
git clone https://github.com/JamesJGoodwin/wreckuests 
git clone https://github.com/jaygreig86/dmitry
git clone https://github.com/jaygreig86/dmitry 
git clone https://github.com/jesparza/peepdf
git clone https://github.com/jesparza/peepdf 

git clone https://github.com/jothatron/blackbox
git clone https://github.com/jothatron/blackbox 
git clone https://github.com/JPaulMora/Pyrit
git clone https://github.com/JPaulMora/Pyrit 
git clone https://github.com/jseidl/GoldenEye
git clone https://github.com/jseidl/GoldenEye 
git clone https://github.com/k4m4/kickthemout
git clone https://github.com/k4m4/kickthemout 
git clone https://github.com/k4m4/onioff
git clone https://github.com/k4m4/onioff 
git clone https://github.com/kamorin/DHCPig
git clone https://github.com/kamorin/DHCPig 
git clone https://github.com/karulis/pybluez
git clone https://github.com/karulis/pybluez 
git clone https://github.com/KeepWannabe/Remot3d
git clone https://github.com/KeepWannabe/Remot3d 

git clone https://github.com/kgretzky/evilginx2
git clone https://github.com/kgretzky/evilginx2 
git clone https://github.com/kuburan/txtool
git clone https://github.com/kuburan/txtool 
git clone https://github.com/LandGrey/pydictor
git clone https://github.com/LandGrey/pydictor 
git clone https://github.com/lanmaster53/recon-ng
git clone https://github.com/lanmaster53/recon-ng 
git clone https://github.com/laramies/theHarvester
git clone https://github.com/laramies/theHarvester 
git clone https://github.com/larsbrinkhoff/httptunnel
git clone https://github.com/larsbrinkhoff/httptunnel 
git clone https://github.com/leapsecurity/InSpy
git clone https://github.com/leapsecurity/InSpy 
git clone https://github.com/lgandx/Responder
git clone https://github.com/lgandx/Responder 
git clone https://github.com/lightos/credmap
git clone https://github.com/lightos/credmap 
git clone https://github.com/linkedin/qark
git clone https://github.com/linkedin/qark 
git clone https://github.com/LionSec/wifresti
git clone https://github.com/LionSec/wifresti 
git clone https://github.com/LionSec/xerosploit
git clone https://github.com/LionSec/xerosploit 
git clone https://github.com/LOoLzeC/Evil-create-framework
git clone https://github.com/LOoLzeC/Evil-create-framework 
git clone https://github.com/LOoLzeC/SH33LL
git clone https://github.com/LOoLzeC/SH33LL 
git clone https://github.com/m4ll0k/Infoga
git clone https://github.com/m4ll0k/Infoga 
git clone https://github.com/m8r0wn/subscraper
git clone https://github.com/m8r0wn/subscraper 
git clone https://github.com/maldevel/IPGeoLocation
git clone https://github.com/maldevel/IPGeoLocation 
git clone https://github.com/Manisso/Crips
git clone https://github.com/Manisso/Crips 
git clone https://github.com/Manisso/fsociety
git clone https://github.com/Manisso/fsociety 
git clone https://github.com/Manisso/Xshell
git clone https://github.com/Manisso/Xshell 
git clone https://github.com/Mebus/cupp
git clone https://github.com/Mebus/cupp 
git clone https://github.com/medbenali/CyberScan
git clone https://github.com/medbenali/CyberScan 
git clone https://github.com/mikeryan/crackle
git clone https://github.com/mikeryan/crackle 
git clone https://github.com/milio48/nk26
git clone https://github.com/milio48/nk26 

git clone https://github.com/mitmproxy/mitmproxy
git clone https://github.com/mitmproxy/mitmproxy 
git clone https://github.com/mnp/xspy
git clone https://github.com/mnp/xspy 
git clone https://github.com/Moham3dRiahi/Th3inspector
git clone https://github.com/Moham3dRiahi/Th3inspector 
git clone https://github.com/Moham3dRiahi/XAttacker
git clone https://github.com/Moham3dRiahi/XAttacker 

git clone https://github.com/moxie0/sslstrip
git clone https://github.com/moxie0/sslstrip 
git clone https://github.com/moyix/creddump
git clone https://github.com/moyix/creddump 
git clone https://github.com/Mr-Un1k0d3r/DKMC
git clone https://github.com/Mr-Un1k0d3r/DKMC 
git clone https://github.com/Hendriyawan/FBUPv2.0
git clone https://github.com/Hendriyawan/FBUPv2.0 
git clone https://github.com/MrSqar-Ye/BadMod
git clone https://github.com/MrSqar-Ye/BadMod 
git clone https://github.com/mschwager/fierce
git clone https://github.com/mschwager/fierce 
git clone https://github.com/mteg/braa
git clone https://github.com/mteg/braa 
git clone https://github.com/nathanlopez/Stitch
git clone https://github.com/nathanlopez/Stitch 
git clone https://github.com/nccgroup/demiguise
git clone https://github.com/nccgroup/demiguise 
git clone https://github.com/nccgroup/Winpayloads
git clone https://github.com/nccgroup/Winpayloads 
git clone https://github.com/Neo-Oli/termux-ubuntu
git clone https://github.com/Neo-Oli/termux-ubuntu 
git clone https://github.com/Neohapsis/bbqsql
git clone https://github.com/Neohapsis/bbqsql 
git clone https://github.com/neoneggplant/EggShell
git clone https://github.com/neoneggplant/EggShell 
git clone https://github.com/nfc-tools/mfcuk
git clone https://github.com/nfc-tools/mfcuk 
git clone https://github.com/nfc-tools/mfoc
git clone https://github.com/nfc-tools/mfoc 
git clone https://github.com/nmilosev/termux-fedora
git clone https://github.com/nmilosev/termux-fedora 
git clone https://github.com/NullArray/AutoSploit
git clone https://github.com/NullArray/AutoSploit 

git clone https://github.com/offensive-security/exploitdb
git clone https://github.com/offensive-security/exploitdb 
git clone https://github.com/OJ/gobuster
git clone https://github.com/OJ/gobuster 
git clone https://github.com/orgcandman/Simple-Fuzzer
git clone https://github.com/orgcandman/Simple-Fuzzer 
git clone https://github.com/OWASP/OWASP-WebScarab
git clone https://github.com/OWASP/OWASP-WebScarab 
git clone https://github.com/OWASP/QRLJacking
git clone https://github.com/OWASP/QRLJacking 
git clone https://github.com/P0cL4bs/WiFi-Pumpkin
git clone https://github.com/P0cL4bs/WiFi-Pumpkin 
git clone https://github.com/p4kl0nc4t/Spammer-Grab
git clone https://github.com/p4kl0nc4t/Spammer-Grab 
git clone https://github.com/pasahitz/zirikatu
git clone https://github.com/pasahitz/zirikatu 
git clone https://github.com/peterpt/eternal_scanner
git clone https://github.com/peterpt/eternal_scanner 
git clone https://github.com/peterpt/get
git clone https://github.com/peterpt/get 
git clone https://github.com/portcullislabs/enum4linux
git clone https://github.com/portcullislabs/enum4linux 
git clone https://github.com/PowerScript/KatanaFramework
git clone https://github.com/PowerScript/KatanaFramework 
git clone https://github.com/PowerShellMafia/PowerSploit
git clone https://github.com/PowerShellMafia/PowerSploit 
git clone https://github.com/qunxyz/proxystrike
git clone https://github.com/qunxyz/proxystrike 
git clone https://github.com/r00t-3xp10it/FakeImageExploiter
git clone https://github.com/r00t-3xp10it/FakeImageExploiter 
git clone https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL
git clone https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL 
git clone https://github.com/r00t-3xp10it/morpheus
git clone https://github.com/r00t-3xp10it/morpheus 
git clone https://github.com/r00t-3xp10it/trojanizer
git clone https://github.com/r00t-3xp10it/trojanizer 
git clone https://github.com/r00tmars/ExploitOnCLI
git clone https://github.com/r00tmars/ExploitOnCLI 
git clone https://github.com/r00tmars/XPL-SEARCH
git clone https://github.com/r00tmars/XPL-SEARCH 
git clone https://github.com/Rajkumrdusad/MyServer
git clone https://github.com/Rajkumrdusad/MyServer 

git clone https://github.com/rand0m1ze/ezsploit
git clone https://github.com/rand0m1ze/ezsploit 
git clone https://github.com/ReFirmLabs/binwalk
git clone https://github.com/ReFirmLabs/binwalk 
git clone https://github.com/threat9/routersploit
git clone https://github.com/threat9/routersploit 
git clone https://github.com/reyammer/shellnoob
git clone https://github.com/reyammer/shellnoob 
git clone https://github.com/rezasp/joomscan
git clone https://github.com/rezasp/joomscan 
git clone https://github.com/Rhi7/shell-scan
git clone https://github.com/Rhi7/shell-scan 
git clone https://github.com/ring0lab/catphish
git clone https://github.com/ring0lab/catphish 
git clone https://github.com/riverloopsec/killerbee
git clone https://github.com/riverloopsec/killerbee 
git clone https://github.com/robertdavidgraham/masscan
git clone https://github.com/robertdavidgraham/masscan 
git clone https://github.com/robertswiecki/intrace
git clone https://github.com/robertswiecki/intrace 
git clone https://github.com/ron190/jsql-injection
git clone https://github.com/ron190/jsql-injection 
git clone https://github.com/royhills/arp-scan
git clone https://github.com/royhills/arp-scan 
git clone https://github.com/ruped24/killchain
git clone https://github.com/ruped24/killchain 
git clone https://github.com/s0lst1c3/eaphammer
git clone https://github.com/s0lst1c3/eaphammer 
git clone https://github.com/s0md3v/Blazy
git clone https://github.com/s0md3v/Blazy 
git clone https://github.com/s0md3v/Hash-Buster
git clone https://github.com/s0md3v/Hash-Buster 
git clone https://github.com/s0md3v/sqlmate
git clone https://github.com/s0md3v/sqlmate 
git clone https://github.com/s0md3v/Striker
git clone https://github.com/s0md3v/Striker 
git clone https://github.com/s0md3v/XSStrike
git clone https://github.com/s0md3v/XSStrike 
git clone https://github.com/sabri-zaki/EasY_HaCk
git clone https://github.com/sabri-zaki/EasY_HaCk 
git clone https://github.com/samratashok/nishang
git clone https://github.com/samratashok/nishang 
git clone https://github.com/samyk/pwnat
git clone https://github.com/samyk/pwnat 
git clone https://github.com/sandalpenyok/kojawafft
git clone https://github.com/sandalpenyok/kojawafft 
git clone https://github.com/Sanix-Darker/DDosy
git clone https://github.com/Sanix-Darker/DDosy 
git clone https://github.com/savio-code/fern-wifi-cracker
git clone https://github.com/savio-code/fern-wifi-cracker 
git clone https://github.com/savio-code/ghost-phisher
git clone https://github.com/savio-code/ghost-phisher 
git clone https://github.com/Screetsec/Brutal
git clone https://github.com/Screetsec/Brutal 
git clone https://github.com/Screetsec/Dracnmap
git clone https://github.com/Screetsec/Dracnmap 
git clone https://github.com/Screetsec/LALIN
git clone https://github.com/Screetsec/LALIN 
git clone https://github.com/Screetsec/TheFatRat
git clone https://github.com/Screetsec/TheFatRat 
git clone https://github.com/Screetsec/Vegile
git clone https://github.com/Screetsec/Vegile 
git clone https://github.com/secretsquirrel/the-backdoor-factory
git clone https://github.com/secretsquirrel/the-backdoor-factory 
git clone https://github.com/securestate/termineter
git clone https://github.com/securestate/termineter 
git clone https://github.com/sensepost/kwetza
git clone https://github.com/sensepost/kwetza 
git clone https://github.com/shawarkhanethicalhacker/D-TECT-1
git clone https://github.com/shawarkhanethicalhacker/D-TECT-1 

git clone https://github.com/shekyan/slowhttptest
git clone https://github.com/shekyan/slowhttptest 
git clone https://github.com/shinnok/johnny
git clone https://github.com/shinnok/johnny 

git clone https://github.com/SilverFoxx/PwnSTAR
git clone https://github.com/SilverFoxx/PwnSTAR 

git clone https://github.com/simsong/bulk_extractor
git clone https://github.com/simsong/bulk_extractor 


git clone https://github.com/Smaash/snitch
git clone https://github.com/Smaash/snitch 
git clone https://github.com/Souhardya/Zerodoor
git clone https://github.com/Souhardya/Zerodoor 
git clone https://github.com/SpiderLabs/deblaze
git clone https://github.com/SpiderLabs/deblaze 
git clone https://github.com/SpiderLabs/jboss-autopwn
git clone https://github.com/SpiderLabs/jboss-autopwn 
git clone https://github.com/sqlmapproject/sqlmap
git clone https://github.com/sqlmapproject/sqlmap 
git clone https://github.com/st42/termux-sudo
git clone https://github.com/st42/termux-sudo 
git clone https://github.com/stamparm/DSSS
git clone https://github.com/stamparm/DSSS 
git clone https://github.com/stamparm/DSVW
git clone https://github.com/stamparm/DSVW 
git clone https://github.com/stamparm/DSXS
git clone https://github.com/stamparm/DSXS 
git clone https://github.com/steve-m/kalibrate-rtl
git clone https://github.com/steve-m/kalibrate-rtl 
git clone https://github.com/StreetSec/Gloom-Framework
git clone https://github.com/StreetSec/Gloom-Framework 
git clone https://github.com/sullo/nikto
git clone https://github.com/sullo/nikto 
git clone https://github.com/SusmithKrishnan/cpscan
git clone https://github.com/SusmithKrishnan/cpscan 
git clone https://github.com/SusmithKrishnan/torghost
git clone https://github.com/SusmithKrishnan/torghost 
git clone https://github.com/swisskyrepo/Wordpresscan
git clone https://github.com/swisskyrepo/Wordpresscan 
git clone https://github.com/T4P4N/IP-FY
git clone https://github.com/T4P4N/IP-FY 

git clone https://github.com/utkusen/leviathan
git clone https://github.com/utkusen/leviathan 
git clone https://github.com/The404Hacking/websploit
git clone https://github.com/The404Hacking/websploit 
git clone https://github.com/thehackingsage/hacktronian
git clone https://github.com/thehackingsage/hacktronian 
git clone https://github.com/ThoughtfulDev/EagleEye
git clone https://github.com/ThoughtfulDev/EagleEye 
git clone https://github.com/tiagorlampert/CHAOS
git clone https://github.com/tiagorlampert/CHAOS 
git clone https://github.com/tiagorlampert/sAINT
git clone https://github.com/tiagorlampert/sAINT 
git clone https://github.com/tomac/yersinia
git clone https://github.com/tomac/yersinia 
git clone https://github.com/trustedsec/ridenum
git clone https://github.com/trustedsec/ridenum 
git clone https://github.com/trustedsec/social-engineer-toolkit
git clone https://github.com/trustedsec/social-engineer-toolkit 
git clone https://github.com/Tuhinshubhra/CMSeeK
git clone https://github.com/Tuhinshubhra/CMSeeK 
git clone https://github.com/Tuhinshubhra/fbvid
git clone https://github.com/Tuhinshubhra/fbvid 
git clone https://github.com/Tuhinshubhra/RED_HAWK
git clone https://github.com/Tuhinshubhra/RED_HAWK 
git clone https://github.com/Tuhinshubhra/shellstack
git clone https://github.com/Tuhinshubhra/shellstack 
git clone https://github.com/Cyb0r9/Androspy
git clone https://github.com/Cyb0r9/Androspy 
git clone https://github.com/Cyb0r9/SocialBox
git clone https://github.com/Cyb0r9/SocialBox 
git clone https://github.com/twelvesec/gasmask
git clone https://github.com/twelvesec/gasmask 
git clone https://github.com/s0md3v/Breacher
git clone https://github.com/s0md3v/Breacher 
git clone https://github.com/s0md3v/ReconDog
git clone https://github.com/s0md3v/ReconDog 
git clone https://github.com/UndeadSec/EvilURL
git clone https://github.com/UndeadSec/EvilURL 
git clone https://github.com/UndeadSec/GoblinWordGenerator
git clone https://github.com/UndeadSec/GoblinWordGenerator 
git clone https://github.com/UndeadSec/SocialFish
git clone https://github.com/UndeadSec/SocialFish 
git clone https://github.com/urbanadventurer/bing-ip2hosts
git clone https://github.com/urbanadventurer/bing-ip2hosts 
git clone https://github.com/urbanadventurer/WhatWeb
git clone https://github.com/urbanadventurer/WhatWeb 
git clone https://github.com/ustayready/CredSniper
git clone https://github.com/ustayready/CredSniper 
git clone https://github.com/v1s1t0r1sh3r3/airgeddon
git clone https://github.com/v1s1t0r1sh3r3/airgeddon 
git clone https://github.com/vanhauser-thc/thc-ipv6
git clone https://github.com/vanhauser-thc/thc-ipv6 
git clone https://github.com/vecna/sniffjoke
git clone https://github.com/vecna/sniffjoke 

git clone https://github.com/volatilityfoundation/volatility
git clone https://github.com/volatilityfoundation/volatility 
git clone https://github.com/websploit/websploit
git clone https://github.com/websploit/websploit 
git clone https://github.com/Wh1t3Rh1n0/air-hammer
git clone https://github.com/Wh1t3Rh1n0/air-hammer 
git clone https://github.com/wifiphisher/wifiphisher
git clone https://github.com/wifiphisher/wifiphisher 

git clone https://github.com/WiPi-Hunter/PiDense
git clone https://github.com/WiPi-Hunter/PiDense 
git clone https://github.com/wireghoul/doona
git clone https://github.com/wireghoul/doona 
git clone https://github.com/wireghoul/dotdotpwn
git clone https://github.com/wireghoul/dotdotpwn 

git clone https://github.com/x90skysn3k/brutespray
git clone https://github.com/x90skysn3k/brutespray 
git clone https://github.com/xHak9x/fbi
git clone https://github.com/xHak9x/fbi 


git clone https://github.com/xmendez/wfuzz
git clone https://github.com/xmendez/wfuzz 
git clone https://github.com/xtr4nge/giskismet
git clone https://github.com/xtr4nge/giskismet 
git clone https://github.com/Xyl2k/Cookie-stealer
git clone https://github.com/Xyl2k/Cookie-stealer 
git clone https://github.com/Zapotek/cdpsnarf
git clone https://github.com/Zapotek/cdpsnarf 
git clone https://github.com/zaproxy/zaproxy
git clone https://github.com/zaproxy/zaproxy 
echo "DOWNLOADING PASSWORD DBS!"
git clone https://github.com/danielmiessler/SecLists/
git clone https://github.com/berzerk0/Probable-Wordlists
wget https://download.weakpass.com/wordlists/1927/cyclone.hashesorg.hashkiller.combined.txt.7z
wget https://crackstation.net/files/crackstation.txt.gz
echo "Finshed!"
echo "Pls support my work by hitting the griidy for ukrain!!!!!"
sleep 10
echo "fortnite.exe has stop responding"
sleep 1
clear
